name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup bats
        uses: actions/setup-node@v1
        run: npm install -g bats

      - name: Run test
        run: cd "$GITHUB_WORKSPACE" && bats test/bahn.bats
